replicaCount: 3

image:
  repository: docker.io/rishikbsr/thoughtworks-mediawiki
  pullPolicy: IfNotPresent
  tag: 1.0.1

serviceAccount:
  create: true
  name: mediawiki-service-account

service:
  name: mediawiki-service
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: mediawiki.isense.qa.forge.connected.honeywell.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: isense-tls
      hosts:
        - mediawiki.isense.qa.forge.connected.honeywell.com

mediawiki:
  fullnameOverride: "mediawiki"

configMap:
  name: mediawiki-config

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0

#affinity:
#  nodeAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: "disk-speed"
#              operator: "In"
#              values:
#                - "fast"
#                - "ssd"
